### ISSUE TITLE
Design/README.md grammar nit

### ISSUE THREAD

**Issue by delicopsch56** [2WAY/Design#1]
"We will add examples in the near future, to explain the concept further."

This may be more grammatically correct\friendly text for native English speakers\grammarians.

"We will add examples in the near future, to further illustrate the concept."

**Comment by livegnik** [comment]
ACK!

Thanks for submitting the first issue ever to this repository! It's a small one, but every bit or byte helps. There's no way I can do this alone, and any kind of comment, suggestion, and or question is welcome.

**Comment by enummela** [comment]
Proposed fix: #2
